Update packaging/linux/linux_agent_builder.sh
Co-authored-by: Lukasz Maksymczuk <tehasdf@users.noreply.github.com>

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -64,24 +64,6 @@ pipeline {
             }
           }
         }
-        stage('build_agent'){
-          steps{
-            sh script: "mkdir -p ${env.WORKSPACE}/build_agent && cp -rf ${env.WORKSPACE}/${env.PROJECT}/. ${env.WORKSPACE}/build_agent", label: "copying repo to separate workspace"
-            container('py310'){
-              dir("${env.WORKSPACE}/build_agent") {
-                sh script: '''
-                  SO_DIR=$(find /usr/lib -name "libffi.so*" -exec dirname {} \\; -quit)
-                  sudo ln -s $SO_DIR/libffi.so.7 $SO_DIR/libffi.so.6
-                ''', label: 'installing prerequisities'
-                sh script: """
-                  curl "https://raw.githubusercontent.com/cloudify-cosmo/cloudify-agent/${env.BRANCH_NAME}/packaging/linux/linux_agent_builder.sh" -o linux_agent_builder.sh
-                  chmod +x linux_agent_builder.sh
-                  ./linux_agent_builder.sh alpine python ${env.VERSION}-${env.PRERELEASE}
-                """.stripIndent().trim(), label: 'creating the agent package'
-              }
-            }
-          }
-        }
         stage('Deploy EC2 instances'){
           steps{
             catchError(message: 'Failure on: cloudify-agent tests', buildResult: 'SUCCESS', stageResult: 'FAILURE') {
@@ -90,22 +72,22 @@ pipeline {
                 setupGithubSSHKey()
                 dir("${env.WORKSPACE}/${env.PROJECT}/jenkins"){
                   withVault([configuration: configuration, vaultSecrets: secrets]){
-                    sh script:"""#!/bin/bash
+                    sh script:'''#!/bin/bash
                       set -euxo pipefail
                       python -m venv .venv
                       source .venv/bin/activate
 
-                      cfy profile use ${env.MANAGER_IP} -u ${env.MANAGER_USERNAME} -p ${env.MANAGER_PASSWORD} -t ${env.MANAGER_TENANT} --ssl
+                      cfy profile use ${MANAGER_IP} -u ${MANAGER_USERNAME} -p ${MANAGER_PASSWORD} -t ${MANAGER_TENANT} --ssl
                       pushd 'bp'
-                        cfy install -b ec2-cfy-agent-tests-blueprint-${env.BRANCH_NAME}-${env.BUILD_NUMBER} ec2-cfy-agent-tests-blueprint.yaml
+                        cfy install -b ec2-cfy-agent-tests-blueprint-${BRANCH_NAME}-${BUILD_NUMBER} ec2-cfy-agent-tests-blueprint.yaml
                       popd
-                      cfy deployments capabilities ec2-cfy-agent-tests-blueprint-${env.BRANCH_NAME}-${env.BUILD_NUMBER} --json > capabilities.json
+                      cfy deployments capabilities ec2-cfy-agent-tests-blueprint-${BRANCH_NAME}-${BUILD_NUMBER} --json > capabilities.json
                       jq -r '.key_content.value' capabilities.json > ~/.ssh/ec2_ssh_key && chmod 600 ~/.ssh/ec2_ssh_key
                       for i in {1..16};
                         do ssh-keyscan -H \$(jq -r '.endpoint.value' capabilities.json) >> ~/.ssh/known_hosts && break || sleep 10;
                       done
                       echo 'ClientAliveInterval 50' >> /etc/ssh/sshd_config
-                    """, label:'Configure and install blueprint on manager'
+                    ''', label:'Configure and install blueprint on manager'
                   }
                 }
               }
@@ -157,35 +139,38 @@ EOT
         stage('build_rpm'){
           steps {
             container('rpmbuild'){
-              sh script: """
+              sh script: '''
                 cd ~/rpmbuild
-                git clone https://github.com/cloudify-cosmo/cloudify-agent.git SOURCES && cd SOURCES && git checkout ${env.BRANCH_NAME}
-              """, label: 'Copying repo to separate workspace'
-              sh script: """
+                git clone https://github.com/cloudify-cosmo/cloudify-agent.git SOURCES && cd SOURCES && git checkout ${BRANCH_NAME}
+              ''', label: 'Copying repo to separate workspace'
+              sh script: '''
                 curl -o ~/rpmbuild/SOURCES/cloudify-agents.spec https://raw.githubusercontent.com/cloudify-cosmo/cloudify-manager/master/packaging/cloudify-agents.spec ;
                 mkdir -p ~/rpmbuild/SOURCES/packaging/agents/ ;
                 curl -o ~/rpmbuild/SOURCES/packaging/agents/copy_packages.py https://raw.githubusercontent.com/cloudify-cosmo/cloudify-manager/master/packaging/agents/copy_packages.py ;
-                """, label: 'Prepare rpm-building environment'
-              sh script: """
+                ''', label: 'Prepare rpm-building environment'
+              sh script: '''
+                #!/usr/bin/env bash
+                set -euxo pipefail
                 cd ~/rpmbuild/SOURCES
 
+                #--- build the agent here
+                cp packaging/linux/linux_agent_builder.sh .
+                chmod +x linux_agent_builder.sh
+                ./linux_agent_builder.sh manylinux none ${VERSION}-${PRERELEASE}
 
-                cp -rf ${env.WORKSPACE}/build_agent/*.tar.gz .
-
-
-
+                # retries because yum mirrors aren't always reliable
                 for i in {1..30}; do yum-builddep -y cloudify-agents.spec && break || sleep 10; done
                 spectool \
-                  -d "CLOUDIFY_VERSION ${env.VERSION}" \
-                  -d "CLOUDIFY_PACKAGE_RELEASE ${env.PRERELEASE}" \
+                  -d "CLOUDIFY_VERSION ${VERSION}" \
+                  -d "CLOUDIFY_PACKAGE_RELEASE ${PRERELEASE}" \
                   -P cloudify-agents.spec \
                   -S -g
                 rpmbuild \
-                  -D "CLOUDIFY_VERSION ${env.VERSION}" \
-                  -D "CLOUDIFY_PACKAGE_RELEASE ${env.PRERELEASE}" \
+                  -D "CLOUDIFY_VERSION ${VERSION}" \
+                  -D "CLOUDIFY_PACKAGE_RELEASE ${PRERELEASE}" \
                   -bb cloudify-agents.spec
-                """, label: 'Building a CI agent rpm'
-              sh script:("mkdir -p ${env.WORKSPACE}/rpm && cp -rf ~/rpmbuild/RPMS/noarch/. ${env.WORKSPACE}/rpm"), label: "Copy RPM to rpm folder"
+                ''', label: 'Building a CI agent rpm'
+              sh script:("mkdir -p ${WORKSPACE}/rpm && cp -rf ~/rpmbuild/RPMS/noarch/. ${WORKSPACE}/rpm"), label: "Copy RPM to rpm folder"
             }
           }
           post {
