RD-5919 agents to py310 (#849)
* RD-5572 Use py3.10 docker image

* RD-5572 Upgrade CI python to 3.10

* RD-5919 Deal with shebangs in agent's python env

* RD-5919 Agent build script for linux

* RD-5919 Update CI

* Update jenkins/Jenkinsfile

Co-authored-by: Lukasz Maksymczuk <tehasdf@users.noreply.github.com>

* Update packaging/linux/linux_agent_builder.sh

Co-authored-by: Lukasz Maksymczuk <tehasdf@users.noreply.github.com>

* Update packaging/linux/linux_agent_builder.sh

Co-authored-by: Lukasz Maksymczuk <tehasdf@users.noreply.github.com>

* Update packaging/linux/linux_agent_builder.sh

Co-authored-by: Lukasz Maksymczuk <tehasdf@users.noreply.github.com>

* RD-5919 Fix tests

* CI: run tests on 3.10 (#854)

* CI: run tests on 3.10

* clean up test-reqs

* avoid coverage

not that easy to make it to work. Would need sqlite.

* pytest -sv

more useful logs

* install wget after all

it is used by the tests themselves

* RD-5982 Use `distro` module to find Linux distribution

* test_configuration: use distro instead of platform

* more s/platform/distro/

also use .get for the os_family. I'm not sure why, but it's not always
there.

Co-authored-by: Mateusz Neumann <mateumann@gmail.com>

* restore a fake build_agent step to placate github

Co-authored-by: Lukasz Maksymczuk <tehasdf@users.noreply.github.com>
Co-authored-by: Mateusz Neumann <mateumann@gmail.com>
Co-authored-by: asdf <tehasdf@gmail.com>

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -54,7 +54,7 @@ pipeline {
         stage('flake8'){
           steps{
             sh script: "mkdir -p ${env.WORKSPACE}/flake8 && cp -rf ${env.WORKSPACE}/${env.PROJECT}/. ${env.WORKSPACE}/flake8", label: "copying repo to separate workspace"
-            container('py36'){
+            container('py310'){
               dir("${env.WORKSPACE}/flake8") {
                 echo 'install flake 8'
                 sh 'pip install flake8 --user'
@@ -66,49 +66,33 @@ pipeline {
         }
         stage('build_agent'){
           steps{
-            sh script: "mkdir -p ${env.WORKSPACE}/build_agent && cp -rf ${env.WORKSPACE}/${env.PROJECT}/. ${env.WORKSPACE}/build_agent", label: "copying repo to separate workspace"
-            container('py36'){
-              dir("${env.WORKSPACE}/build_agent") {
-                sh script: '''
-                  python3 -m venv packager_env
-                  . packager_env/bin/activate
-                  pip install https://github.com/cloudify-cosmo/cloudify-agent-packager/archive/master.zip
-                  cp packaging/local.ini centos8.ini
-                  cat >>centos8.ini <<EOF
-                  [system]
-                  distribution=centos
-                  release=8
-                  EOF
-                  cfy-ap -f -v -c centos8.ini
-                  '''.stripIndent().trim(), label: 'creating the agent package'
-              }
-            }
+            echo "this does nothing, and should be removed after the build_agent step is made non-required in github"
           }
         }
         stage('Deploy EC2 instances'){
           steps{
             catchError(message: 'Failure on: cloudify-agent tests', buildResult: 'SUCCESS', stageResult: 'FAILURE') {
-              container('py36'){
+              container('py310'){
                 echo 'Setup Github SSH key'
                 setupGithubSSHKey()
                 dir("${env.WORKSPACE}/${env.PROJECT}/jenkins"){
                   withVault([configuration: configuration, vaultSecrets: secrets]){
-                    sh script:"""#!/bin/bash
+                    sh script:'''#!/bin/bash
                       set -euxo pipefail
                       python -m venv .venv
                       source .venv/bin/activate
 
-                      cfy profile use ${env.MANAGER_IP} -u ${env.MANAGER_USERNAME} -p ${env.MANAGER_PASSWORD} -t ${env.MANAGER_TENANT} --ssl
+                      cfy profile use ${MANAGER_IP} -u ${MANAGER_USERNAME} -p ${MANAGER_PASSWORD} -t ${MANAGER_TENANT} --ssl
                       pushd 'bp'
-                        cfy install -b ec2-cfy-agent-tests-blueprint-${env.BRANCH_NAME}-${env.BUILD_NUMBER} ec2-cfy-agent-tests-blueprint.yaml
+                        cfy install -b ec2-cfy-agent-tests-blueprint-${BRANCH_NAME}-${BUILD_NUMBER} ec2-cfy-agent-tests-blueprint.yaml
                       popd
-                      cfy deployments capabilities ec2-cfy-agent-tests-blueprint-${env.BRANCH_NAME}-${env.BUILD_NUMBER} --json > capabilities.json
+                      cfy deployments capabilities ec2-cfy-agent-tests-blueprint-${BRANCH_NAME}-${BUILD_NUMBER} --json > capabilities.json
                       jq -r '.key_content.value' capabilities.json > ~/.ssh/ec2_ssh_key && chmod 600 ~/.ssh/ec2_ssh_key
                       for i in {1..16};
                         do ssh-keyscan -H \$(jq -r '.endpoint.value' capabilities.json) >> ~/.ssh/known_hosts && break || sleep 10;
                       done
                       echo 'ClientAliveInterval 50' >> /etc/ssh/sshd_config
-                    """, label:'Configure and install blueprint on manager'
+                    ''', label:'Configure and install blueprint on manager'
                   }
                 }
               }
@@ -122,33 +106,50 @@ pipeline {
         stage('Configure & Run-tests on EC2 instance'){
           steps{
             catchError(message: 'Failure on: cloudify-agent tests', buildResult: 'SUCCESS', stageResult: 'FAILURE') {
-              container('py36'){
+              container('py310'){
                 dir("${env.WORKSPACE}/${env.PROJECT}/jenkins"){
                   withVault([configuration: configuration, vaultSecrets: secrets]){
-                    sh script:"""#!/bin/bash
-                      ssh -i ~/.ssh/ec2_ssh_key -l centos \$(cat capabilities.json | jq '.endpoint.value' | tr -d '"') /bin/bash << 'EOT'
-set -ex
-sudo yum install -y epel-release git vim python-virtualenv
+                    sh script:"""
+                      ssh -i ~/.ssh/ec2_ssh_key -l centos \$(jq -r '.endpoint.value' capabilities.json) /bin/bash -ex << 'EOT'
+# install & start rabbitmq
+sudo yum install -y epel-release git wget
 sudo yum install -y rabbitmq-server
-sudo yum install -y wget
-sudo yum install -y python3
-git clone https://github.com/cloudify-cosmo/cloudify-agent.git
 sudo systemctl enable rabbitmq-server
 sudo systemctl start rabbitmq-server
-python3 -m venv py3
-source py3/bin/activate
-pip install --upgrade pip setuptools
-export LC_ALL=en_US.utf-8
-export LANG=en_US.utf-8
+
+# setup python3.10
+curl -fL --retry 5 \
+  https://cloudify-cicd.s3.amazonaws.com/python-build-packages/cfy-python3.10.tgz \
+  -o cfy-python3.10.tgz
+mkdir python3.10
+tar --strip-components=2 -zxf cfy-python3.10.tgz -C python3.10
+python3.10/bin/python3.10 -m venv venv
+set +x  # going to activate the venv, hide activate output
+. venv/bin/activate
+set -x
+
+# fetch the code
+git clone https://github.com/cloudify-cosmo/cloudify-agent.git \
+  --branch "${env.BRANCH_NAME}" \
+  --single-branch \
+  --depth 1
+
 pushd cloudify-agent
-git checkout ${env.BRANCH_NAME}
-pip install -r test-requirements.txt
-pip install -r dev-requirements.txt
-pip install '.[fabric]'
-echo 'run py3.6 tests'
-pytest --run-rabbit-tests --run-ci-tests --cov-report term-missing --cov=cloudify_agent cloudify_agent --junitxml=test-results/cloudify_agent_py3.xml
+  # install prereqs
+  pip install --upgrade pip setuptools
+  pip install -r test-requirements.txt
+  pip install -r dev-requirements.txt
+  pip install '.[fabric]'
+
+  # run all tests
+  pytest \
+    -sv \
+    --run-rabbit-tests \
+    --run-ci-tests \
+    cloudify_agent \
+    --junitxml=test-results/cloudify_agent_py3.xml
 popd
-deactivate
+
 EOT
                     """, label: 'Prepare instance and run pytests'
                   }
@@ -160,30 +161,38 @@ EOT
         stage('build_rpm'){
           steps {
             container('rpmbuild'){
-              sh script: """
+              sh script: '''
                 cd ~/rpmbuild
-                git clone https://github.com/cloudify-cosmo/cloudify-agent.git SOURCES && cd SOURCES && git checkout ${env.BRANCH_NAME}
-              """, label: 'Copying repo to separate workspace'
-              sh script: """
+                git clone https://github.com/cloudify-cosmo/cloudify-agent.git SOURCES && cd SOURCES && git checkout ${BRANCH_NAME}
+              ''', label: 'Copying repo to separate workspace'
+              sh script: '''
                 curl -o ~/rpmbuild/SOURCES/cloudify-agents.spec https://raw.githubusercontent.com/cloudify-cosmo/cloudify-manager/master/packaging/cloudify-agents.spec ;
                 mkdir -p ~/rpmbuild/SOURCES/packaging/agents/ ;
                 curl -o ~/rpmbuild/SOURCES/packaging/agents/copy_packages.py https://raw.githubusercontent.com/cloudify-cosmo/cloudify-manager/master/packaging/agents/copy_packages.py ;
-                """, label: 'Prepare rpm-building environment'
-              sh script: """
+                ''', label: 'Prepare rpm-building environment'
+              sh script: '''
+                #!/usr/bin/env bash
+                set -euxo pipefail
                 cd ~/rpmbuild/SOURCES
-                cp -rf ${env.WORKSPACE}/build_agent/*.tar.gz .
+
+                #--- build the agent here
+                cp packaging/linux/linux_agent_builder.sh .
+                chmod +x linux_agent_builder.sh
+                ./linux_agent_builder.sh manylinux none ${VERSION}-${PRERELEASE}
+
+                # retries because yum mirrors aren't always reliable
                 for i in {1..30}; do yum-builddep -y cloudify-agents.spec && break || sleep 10; done
                 spectool \
-                  -d "CLOUDIFY_VERSION ${env.VERSION}" \
-                  -d "CLOUDIFY_PACKAGE_RELEASE ${env.PRERELEASE}" \
+                  -d "CLOUDIFY_VERSION ${VERSION}" \
+                  -d "CLOUDIFY_PACKAGE_RELEASE ${PRERELEASE}" \
                   -P cloudify-agents.spec \
                   -S -g
                 rpmbuild \
-                  -D "CLOUDIFY_VERSION ${env.VERSION}" \
-                  -D "CLOUDIFY_PACKAGE_RELEASE ${env.PRERELEASE}" \
+                  -D "CLOUDIFY_VERSION ${VERSION}" \
+                  -D "CLOUDIFY_PACKAGE_RELEASE ${PRERELEASE}" \
                   -bb cloudify-agents.spec
-                """, label: 'Building a CI agent rpm'
-              sh script:("mkdir -p ${env.WORKSPACE}/rpm && cp -rf ~/rpmbuild/RPMS/noarch/. ${env.WORKSPACE}/rpm"), label: "Copy RPM to rpm folder"
+                ''', label: 'Building a CI agent rpm'
+              sh script:("mkdir -p ${WORKSPACE}/rpm && cp -rf ~/rpmbuild/RPMS/noarch/. ${WORKSPACE}/rpm"), label: "Copy RPM to rpm folder"
             }
           }
           post {
@@ -206,7 +215,7 @@ EOT
     stage('Copy test results'){
       steps{
         catchError(message: 'Failure on: cloudify-agent tests copy', buildResult: 'SUCCESS', stageResult: 'FAILURE') {
-          container('py36'){
+          container('py310'){
             dir("${env.WORKSPACE}/${env.PROJECT}/jenkins"){
               withVault([configuration: configuration, vaultSecrets: secrets]){
                 sh script:"""#!/bin/bash
@@ -219,10 +228,10 @@ EOT
         }
       }
     }
-    stage('Terminate py36 instance'){ // we made github to wait on a job with this exact name, typo included
+    stage('Terminate py310 instance'){
       steps{
         catchError(message: 'Failure on: cloudify-agent tests', buildResult: 'SUCCESS', stageResult: 'FAILURE') {
-          container('py36'){
+          container('py310'){
             dir("${env.WORKSPACE}/${env.PROJECT}/jenkins"){
               withVault([configuration: configuration, vaultSecrets: secrets]){
                 echo 'Uninstall and delete blueprint from manager'
